[nginx]
logfile = '/var/log/nginx/stats.log'

[graphite]
server = 'localhost:8999'
interval = 10

[[report]]
label = 'api'
upstream = 'api'
host = 'api.telemetryapp.com'
statuses = [200, 201, 400, 500, 502, 503]
methods = ["POST"]
uri_regex = ''
